### PR TITLE
Dropzone, added DragEnd property to allow executing logic when a drag operation ends

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
see #96

### CODE REVIEW

**Comment by Postlagerkarte** [comment]
Looks great! Thanks.

**Comment by ViRuSTriNiTy** [comment]
@Postlagerkarte Would you please release a new NuGet package? Otherwise I need to work with a git submodule and this is somewhat tedious.

**Comment by tkrakowiak** [comment]
@ViRuSTriNiTy DragDropService is reset (DragDropService.ActiveItem = default) before DragEnd is called resulting in null being passed as parameter to DragEnd.

**Comment by ViRuSTriNiTy** [comment]
@tkrakowiak Can you provide a minimal reproducible example?

**Comment by tkrakowiak** [comment]
@ViRuSTriNiTy here you go:

    <Dropzone Items="MyToDoList" DragEnd="DragEnd">
        <Todo OnRemoveClick="(item)=>MyToDoList.Remove(item)" Item="@context"></Todo>
    </Dropzone>

    private void DragEnd(TodoItem obj)
    {
        var todo = obj;
    }

**Comment by tkrakowiak** [comment]
@ViRuSTriNiTy I think this PR would be enough to fix it.

https://github.com/Postlagerkarte/blazor-dragdrop/pull/119

**Pull request merged**
