### PR TITLE
Event handling logic changes, dropzone group support and a few cosmetic changes

### PR DESCRIPTION
**Pull request by rdm1234**
Support for groups of dropzones, allows you to restrict movement of objects between several dropzones, and also allows you to create nested dropzones

### CODE REVIEW

**Comment by Postlagerkarte** [comment]
Hi @rdm1234 ! Thanks a lot for this contribution.  I have not yet merged it because I am not sure  if it covers the requirements given in #8  -  Would you mind updating your PR to show e.g a draggable treeview or some of the other use cases pointed out in the nested draggable issue?

**Comment by rdm1234** [comment]
Hi @Postlagerkarte 
I changed the event handling logic for the dropzones, because during the creation of the second example of nested dropzones, I discovered a problem with incorrect event handling due to a delay in selecting the current element (because of this, checks in the event handling methods worked somewhere wrong).
It was too difficult for me to debug with the old logic, as there were a lot of conditions that are difficult to track.
It seems to me that the new event handling logic will help make development more flexible - it will be easier to debug existing code and add new functions for handling events.
It seems to me that the performance will be approximately equal. Now, for the dropzones, into which the drop is impossible, there will be no check actions, while each time you start OnDragStart, some of the dropzones will simply change states.

**Comment by rdm1234** [comment]
I added a second example of working with nested dropzones - does it fit the requirements of #8?

**Comment by StefH** [comment]
@rdm1234 Nice functionality !

@Postlagerkarte : can you merge this to master?

**Comment by Postlagerkarte** [comment]
Yes, this is a cool feature and great work by @rdm1234 !  However, it throws exceptions when using InstantSwap mode. What is more, this is key feature, which needs some additional testing, either manually by some volunteers or preferably by having some unit tests.  Hope this explains why this is still not merged.

**Comment by StefH** [comment]
Hello @Postlagerkarte:

- can you point out the scenario where that exception is thrown when using InstantReplace = true ? Because I don't see it (yet) in my example application.
- unit tests are always useful, maybe @rdm1234 can add these?
- I can volunteer for testing if that helps you

**Comment by rdm1234** [comment]
Hi I've found that it's better to split swap and instant replace functions. There are bugs in the current code in master (code below) - GIFs below.

```
private void Swap(TItem draggedOverItem, TItem activeItem)
    {
        var indexDraggedOverItem = Items.IndexOf((TItem)draggedOverItem);
        var indexActiveItem = Items.IndexOf((TItem)activeItem);

        if (indexActiveItem == -1) // item is new to the dropzone
        {
            //insert into new zone
            Items.Insert(indexDraggedOverItem + 1, activeItem);
            //remove from old zone
            DragDropService.Items.Remove(activeItem);
        }
        else //swap the items
        {
            if (indexDraggedOverItem == indexActiveItem) return;
            TItem tmp = Items[indexDraggedOverItem];
            Items[indexDraggedOverItem] = Items[indexActiveItem];
            Items[indexActiveItem] = tmp;
        }
    }
```

GIF 1

GIF 2

In code with [this change](https://github.com/Postlagerkarte/blazor-dragdrop/pull/63/commits/16e91b5728440b95e65304ec507bdf367a7a0d31#diff-50bd9c4c0a7c9d7b9120c3544ecc276ed9c5dec3a89b00d123db2f4ee69f46e2) there were logic to process swap correctly but I forgot about instant replace, so it didn't work at all. So now I've [added new method](https://github.com/Postlagerkarte/blazor-dragdrop/pull/63/commits/dcbc423a65b58d97e5180acd46670d42800ca3b0#diff-50bd9c4c0a7c9d7b9120c3544ecc276ed9c5dec3a89b00d123db2f4ee69f46e2) to process instant replace (similar to code from Swap method current plk master but with one line fixing problem shown in GIF 1).

**Comment by rdm1234** [comment]
I've [added id tag to the dropzone div](https://github.com/Postlagerkarte/blazor-dragdrop/pull/63/commits/1ac8e211c170244a914f1c99c7b2c8a09f87db9d) - some unit tests didn't work, because the Id parameter was not passed for the dropzone div.

**Comment by rdm1234** [comment]
Hi @StefH!
I don't know how much time I will be able to devote to unit tests in the near future, but if I can free some time, I will write a couple of tests. But most likely it won't be very soon.

**Comment by rdm1234** [comment]
For now because of #75 instant swap does not work correctly for the nested dropzone example 2 ([this one](https://github.com/Postlagerkarte/blazor-dragdrop/pull/63/commits/dcbc423a65b58d97e5180acd46670d42800ca3b0#diff-1c0292e7c6ddd378d2c9d3c95fc2684a59ff8358dae624abbc291bcf265b0528)) because of the difference in height between some elements.

**Comment by StefH** [comment]
@Postlagerkarte  and @rdm1234 

For what's worth : I'm able to use this latest code in my example project without any issues (as far I could test it).
Example project : https://github.com/StefH/BlazorDragAndDrop
Demo: https://blazordraganddrop.azurewebsites.net/ (**Form** page has nested items)

**Comment by rdm1234** [comment]
@StefH 

At the moment, I also checked manually, I found a problem with the first attempt to move an element to another drop zone - to swap, you must first hover the mouse over the spacing between the elements, and then only at the element itself with which you need to swap, but this only works on the first hover, and then when you walk around the zone, everything works as it should.

As I understand it, the demo page is currently taking the last code I added, so you can also check it here: https://blazordragdrop.azurewebsites.net/nesteddifferentviews

**Comment by Postlagerkarte** [comment]
Great work guys! Keep it up! 

Only quickly played around with the demo and seems to have an issue updating correctly: 

freeze

Can you confirm?

**Comment by StefH** [comment]
I can confirm this.

Only happens when moving sections to sub-sections I think?

**Comment by rdm1234** [comment]
@StefH Can you please check with this update: https://github.com/Postlagerkarte/blazor-dragdrop/pull/63/commits/36ec11209a7771e2bea14a880c96bfa4c5b7189a

**Comment by StefH** [comment]
@rdm1234 I did copy your latest code and it seems to work fine: Demo: https://blazordraganddrop.azurewebsites.net/ (Form page has nested items)

**Comment by StefH** [comment]
@rdm1234 Can you please fix merge conflicts?

@Postlagerkarte : if these merge conflicts are resolved, can you please create a new NuGet ?

**Comment by rdm1234** [comment]
> @rdm1234 Can you please fix merge conflicts?

I don't have write access to this repository, so i can't fix conflicts

**Comment by ViRuSTriNiTy** [comment]
I really need the nested draggable feature. Since I cannot add commits to this PR and @rdm1234 does not seem to care I tried to fix the merge conflicts in https://github.com/ViRuSTriNiTy/blazor-dragdrop/tree/nested-draggables

I took me like 3 hours to somehow get my head around what @rdm1234 is doing here. Basically the rename and complete removal of whole blocks from `Dropzone.razor` in favor of adding several classes make a merge an absolute hell.

Anyway, I got it working ... at least it compiles and the demos seem working. Sadly the tests all fails but no wonder when considering the heavy restructuring of the code.

@Postlagerkarte How should be continue? Close this PR and create a new one from https://github.com/ViRuSTriNiTy/blazor-dragdrop/tree/nested-draggables and perhaps @StefH can review the PR?

**Comment by Postlagerkarte** [comment]
Hi @ViRuSTriNiTy  and welcome :)

I never merged this PR because the code itself was pretty invasive and broke my mental model of the existing code. What is more, I found it behaved erratic in specific circumstances (not having any tests did not increase my confidence either.) Last but not least I was not too happy with the usability , found it a bit cumbersome.  How do you feel about those issues?

**Comment by ViRuSTriNiTy** [comment]
@Postlagerkarte I'm pretty much sharing your opinion.

My plan is to continue working on the code provided by @rdm1234 to first get it working for my case. Then we should start reviewing all parts (demos, tests, tweaks added in the past before I was even aware of this project and so on) to avoid breaking things when we decide to merge it to master.

The thing is that currently we are blocked here because @rdm1234 does not answer and editing this PR is not possible. So we should close it and continue working in another one.

What do you think?

**Comment by Postlagerkarte** [comment]
Yep, sounds good. Good ahead.

**Pull request closed without merging**
