### PR TITLE
added support for virtualization

### LINKED ISSUE #163: How to use it with Virtualization?
I use this library but can't figure out how to use it with <Virtualize component of Blazor
.Maybe inside this library Virtualization should be supported=

### PR DESCRIPTION
**Pull request by vladopandzic**
With this I added support for Virtualization.
It should resolve https://github.com/Postlagerkarte/blazor-dragdrop/issues/163
I needed this since I have list of 300 items which are very slow to render and virtualization it actually works great. Sorting doesn't have any issues with added virtualization.

### CODE REVIEW

**Comment by Postlagerkarte** [comment]
Great job on this pull request!

**Comment by vladop** [comment]
I am interested when new nugets are released? I also see pipeline is failing for some reason

**Comment by vladop** [comment]
@Postlagerkarte Please do you have information about the fact when the new nuget packages are released? If it will not happen in the next few weeks, one solution would be to copy source code in my project or manually build nuget and put in my own package source but I wouldn't do that if new release will happen in a reasonable timeframe.

**Comment by Postlagerkarte** [comment]
Sure, I just published the 2.6.1with you changes right now, thanks again for you work!

**Pull request merged**
