### PR TITLE
Allow nesting of `Dropzone` component

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
see #8, PR contains changes from #63 but focused on changes required to allow nested draggables, so no bells and whistles to simplify implementation or opinionated API.

### CODE REVIEW

**Comment by ViRuSTriNiTy** [comment]
@Postlagerkarte I'm surprised that it was that easy to enable nesting. Basically the issue was that nested Dropzones propagated it's event to the parent whereas the drag operation was triggered there. I got the solution from [`36ec112` (#63)](https://github.com/Postlagerkarte/blazor-dragdrop/pull/63/commits/36ec11209a7771e2bea14a880c96bfa4c5b7189a) so the PR was not created in vain.

I think we can merge this now.

**Comment by Postlagerkarte** [comment]
Cool! Feel free to merge. We can add some documentation later.

**Comment by ViRuSTriNiTy** [comment]
@Postlagerkarte Great, merged. How do you handle the versioning of the package? Should we create a milestone which includes multiple issues / PRs for transparency?

**Comment by Postlagerkarte** [comment]
I will create a new release and add what has changed in the description:
https://github.com/Postlagerkarte/blazor-dragdrop/releases

**Comment by ViRuSTriNiTy** [comment]
Ok, so there is a button to create a release on that page. Didn't know that. Thanks.

**Comment by action0jackson** [comment]
@ViRuSTriNiTy Is it possible to find a working example with code of this somewhere.  I have been unable to get a working example of this.  I cannot for the life of me get this to work.  Any help is much appreciated!

**Comment by ViRuSTriNiTy** [comment]
@action0jackson Are the sources of the app you are showing available somewhere for review?

**Comment by action0jackson** [comment]
> @action0jackson Are the sources of the app you are showing available somewhere for review?

@ViRuSTriNiTy unfortunately this is code for a work application.  I will try and mock up a simpler example tomorrow and get back to you.

**Comment by action0jackson** [comment]
@ViRuSTriNiTy @Postlagerkarte I have created an example and put it in the following repository.  I really appreciate your help.

https://github.com/action0jackson/BlazorDragDropExample

**Comment by action0jackson** [comment]
@ViRuSTriNiTy I finally figured out what my issue was. I had copied the css file from the readme.  But I had to comment out the following section to get the drag/drop into the nested dropzone to work.

```css
.plk-dd-inprogess > * {
    pointer-events: none;
}
```
Maybe something to mention.  Thanks for your help!  Sorry if I wasted your time.

**Comment by Postlagerkarte** [comment]
Removing the selector might cause flickering. Try some enter/leave/enter drag movements over your divs and see if it still works.

**Comment by action0jackson** [comment]
> Removing the selector might cause flickering. Try some enter/leave/enter drag movements over your divs and see if it still works.

I didn't notice any flickering dragging around or any testing I have done thus far, but without this selector commented out it simply will not work to drag into a nested dropzone (at least in my example).

**Pull request merged**
